"""
LLM-based Neuron Labels — Cache-Only Loader.

Labels are pre-generated by the offline labeling pipeline
(labeling/run_labeling_pipeline.sh) and stored as JSON in data/.

Expected file: data/llm_labels_{model_id}_llm.json
"""

import json
import os
from pathlib import Path
from typing import Dict, List


def _load_label_cache(data_dir: str, model_id: str) -> Dict[int, dict]:
    cache_path = os.path.join(data_dir, f"llm_labels_{model_id}_llm.json")
    if not os.path.exists(cache_path):
        return {}
    with open(cache_path, "r") as f:
        raw = json.load(f)
    return {int(k): v for k, v in raw.items()}


def get_llm_labels(
    model_id: str,
    data_dir: str = None,
    **_kwargs,
) -> Dict[int, dict]:
    """Load pre-computed LLM labels from cache."""
    if data_dir is None:
        data_dir = str(Path(__file__).parent / "data")
    labels = _load_label_cache(data_dir, model_id)
    if labels:
        print(f"[LLM-Labeling] Loaded {len(labels)} cached labels for {model_id}")
    return labels


def label_neurons_by_ids_llm(
    neuron_ids: List[int],
    model_id: str,
    data_dir: str = None,
    **_kwargs,
) -> Dict[int, dict]:
    """Return cached labels for the requested neuron IDs."""
    if data_dir is None:
        data_dir = str(Path(__file__).parent / "data")
    cache = _load_label_cache(data_dir, model_id)
    return {nid: cache[nid] for nid in neuron_ids if nid in cache}
