"""
Text-based steering using Sentence-BERT embeddings matched against LLM-labeled
SAE neuron concepts.

Each SAE neuron has a human-readable label and description (generated by LLM
from activation patterns). We embed these descriptions and match user queries
against them using cosine similarity. This gives concept-level control:
the user can say "dark sci-fi noir like Minority Report" and we find the
neurons labeled with matching themes.

Uses sentence-transformers (all-MiniLM-L6-v2) -- ~80 MB, fast inference.
"""

import json
import os
import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

DATA_DIR = Path(__file__).parent / "data"

# ---------------------------------------------------------------------------
# Lazy singletons
# ---------------------------------------------------------------------------
_sbert_model = None
_concept_indices: Dict[str, Dict] = {}

MAX_NEURON_MOVIES = 5000
MIN_NEURON_MOVIES = 20


def _get_sbert():
    global _sbert_model
    if _sbert_model is None:
        from sentence_transformers import SentenceTransformer
        _sbert_model = SentenceTransformer('all-MiniLM-L6-v2')
    return _sbert_model


def _get_concept_index(model_id: str = "www_TopKSAE_8192") -> Dict:
    """Build or return a cached concept index from LLM labels.

    The index contains:
      neuron_ids   – list[int]
      labels       – list[str]
      descriptions – list[str]
      tags_text    – list[str]        (genres + tags concatenated)
      embeddings   – np.ndarray (N, D) of description embeddings
      act_counts   – list[int]
    """
    global _concept_indices
    if model_id in _concept_indices:
        return _concept_indices[model_id]

    llm_path = DATA_DIR / f"llm_labels_{model_id}_llm.json"
    if not llm_path.exists():
        for p in DATA_DIR.glob("llm_labels_*_llm.json"):
            llm_path = p
            break

    if not llm_path.exists():
        raise FileNotFoundError(f"No LLM label file found in {DATA_DIR}")

    with open(llm_path, 'r', encoding='utf-8') as f:
        raw = json.load(f)

    neuron_ids, labels, descriptions, tags_text, act_counts = [], [], [], [], []
    for nid_str, info in raw.items():
        label = info.get('label', '')
        desc = info.get('description', '')
        ac = int(info.get('activation_count', 0) or 0)
        if not label or not desc:
            continue
        if ac < MIN_NEURON_MOVIES or ac > MAX_NEURON_MOVIES:
            continue
        if label.lower().startswith('feature ') or label.lower().startswith('neuron '):
            continue
        neuron_ids.append(int(nid_str))
        labels.append(label)
        descriptions.append(desc)
        genres = info.get('genres', [])
        tags = info.get('tags', [])
        tags_text.append(', '.join(genres + tags))
        act_counts.append(ac)

    print(f"[TextSteering] Building concept index: {len(neuron_ids)} neurons from {llm_path.name}")

    model = _get_sbert()
    embed_texts = [f"{lbl}. {desc}" for lbl, desc in zip(labels, descriptions)]
    embeddings = model.encode(embed_texts, show_progress_bar=False, normalize_embeddings=True)

    _concept_indices[model_id] = {
        "neuron_ids": neuron_ids,
        "labels": labels,
        "descriptions": descriptions,
        "tags_text": tags_text,
        "embeddings": np.array(embeddings),
        "act_counts": act_counts,
    }
    print(f"[TextSteering] Concept index ready ({len(neuron_ids)} concepts, embed dim={embeddings.shape[1]})")
    return _concept_indices[model_id]


# ---------------------------------------------------------------------------
# Polarity / sentiment detection
# ---------------------------------------------------------------------------

POSITIVE_INDICATORS = [
    r"\bmore\b", r"\bwant\b", r"\blike\b", r"\blove\b", r"\bprefer\b",
    r"\bincrease\b", r"\badd\b", r"\byes\b", r"\bdefinitely\b", r"\bplease\b",
    r"\bgive me\b", r"\bshow me\b", r"\bfind\b", r"\bsimilar to\b",
    r"\bvíce\b", r"\bchci\b", r"\blíbí\b", r"\bmiluju\b", r"\bpreferuji\b",
    r"\bhledej\b", r"\bnajdi\b", r"\bpodobné\b",
]

NEGATIVE_INDICATORS = [
    r"\bless\b", r"\bno\b", r"\bnot\b", r"\bdon't\b", r"\bdont\b", r"\bhate\b",
    r"\bdislike\b", r"\breduce\b", r"\bremove\b", r"\bwithout\b",
    r"\bavoid\b", r"\bnever\b", r"\bstop\b", r"\bfewer\b",
    r"\bdon't like\b", r"\bdont like\b", r"\bdo not\b", r"\bno more\b",
    r"\bsuppress\b", r"\binhibit\b", r"\bpotlač\b",
    r"\bméně\b", r"\bnechci\b", r"\bbez\b", r"\bžádné\b",
]

COMPOUND_NEGATIVES = [
    r"\bdo not like\b", r"\bdon't like\b", r"\bdo not want\b", r"\bdon't want\b",
    r"\babsolutely not\b", r"\babsolutely no\b", r"\bdefinitely not\b",
    r"\bnever want\b", r"\bnot at all\b",
]

CONNECTIVE_SPLIT = re.compile(
    r'[,;]|\band\b|\bbut\b|\balso\b|\bhowever\b|\ba\b|\bale\b|\btaké\b',
    re.IGNORECASE,
)


def _has_indicator(text: str, indicators: list) -> bool:
    return any(re.search(p, text) for p in indicators)


def _find_indicator_pos(text: str, indicators: list) -> int:
    for p in indicators:
        m = re.search(p, text)
        if m:
            return m.start()
    return 999


def _remove_indicators(text: str, indicators: list) -> str:
    result = text
    for p in COMPOUND_NEGATIVES:
        result = re.sub(p, '', result, flags=re.IGNORECASE)
    for p in indicators:
        result = re.sub(p, '', result, flags=re.IGNORECASE)
    return re.sub(r'\s+', ' ', result).strip()


def split_by_polarity(text: str) -> Tuple[List[str], List[str]]:
    """Split text into (positive_parts, negative_parts)."""
    parts = CONNECTIVE_SPLIT.split(text.lower())
    parts = [p.strip() for p in parts if p.strip()]

    positive, negative = [], []
    for part in parts:
        is_neg = _has_indicator(part, NEGATIVE_INDICATORS)
        is_pos = _has_indicator(part, POSITIVE_INDICATORS)

        if is_neg and not is_pos:
            cleaned = _remove_indicators(part, NEGATIVE_INDICATORS)
            if cleaned:
                negative.append(cleaned)
        elif is_pos and not is_neg:
            positive.append(part)
        else:
            neg_p = _find_indicator_pos(part, NEGATIVE_INDICATORS)
            pos_p = _find_indicator_pos(part, POSITIVE_INDICATORS)
            if neg_p < pos_p:
                cleaned = _remove_indicators(part, NEGATIVE_INDICATORS)
                if cleaned:
                    negative.append(cleaned)
            else:
                positive.append(part)

    if not positive and not negative:
        positive = [text.lower()]

    return positive, negative


# ---------------------------------------------------------------------------
# Core: match text against concept embeddings
# ---------------------------------------------------------------------------

def _cosine_batch(query: np.ndarray, corpus: np.ndarray) -> np.ndarray:
    q = query / (np.linalg.norm(query) + 1e-8)
    return corpus @ q


def text_to_concept_adjustments(
    text: str,
    model_id: str = "www_TopKSAE_8192",
    top_k: int = 7,
    sensitivity: float = 1.0,
) -> Tuple[Dict[int, float], List[Dict]]:
    """Convert text to neuron adjustments by matching against LLM concept labels.

    Returns:
        (adjustments_dict, top_features_list)
        - adjustments_dict: {neuron_id: weight} for ALL matched neurons
        - top_features_list: top-K features for UI display with polarity
    """
    if not text or not text.strip():
        return {}, []

    idx = _get_concept_index(model_id)
    model = _get_sbert()
    neuron_ids = idx["neuron_ids"]
    labels = idx["labels"]
    descriptions = idx["descriptions"]
    embeddings = idx["embeddings"]
    act_counts = idx["act_counts"]

    positive_parts, negative_parts = split_by_polarity(text)
    print(f"[TextSteering] Positive: {positive_parts}")
    print(f"[TextSteering] Negative: {negative_parts}")

    adjustments: Dict[int, float] = {}
    top_features: List[Dict] = []
    seen_labels: set = set()

    SIM_THRESHOLD = 0.30

    def _process(query_text: str, direction: str, top_n: int):
        emb = model.encode(query_text, normalize_embeddings=True)
        sims = _cosine_batch(emb, embeddings)

        ranking = np.argsort(sims)[::-1]
        added = 0
        for rank_idx in ranking:
            if added >= top_n:
                break
            sim = float(sims[rank_idx])
            if sim < SIM_THRESHOLD:
                break

            nid = neuron_ids[rank_idx]
            lbl = labels[rank_idx]
            desc = descriptions[rank_idx]
            mc = act_counts[rank_idx]

            norm_lbl = lbl.lower().strip()
            if norm_lbl in seen_labels:
                continue

            sign = 1.0 if direction == "boost" else -1.0
            weight = sign * sim * sensitivity

            adjustments[nid] = adjustments.get(nid, 0.0) + weight

            seen_labels.add(norm_lbl)
            top_features.append({
                "neuron_id": nid,
                "label": lbl,
                "description": desc,
                "movie_count": mc,
                "weight": round(float(weight), 3),
                "similarity": round(sim, 3),
                "direction": direction,
            })
            added += 1

            print(f"[TextSteering]   {'↑' if direction == 'boost' else '↓'} N{nid} "
                  f"{lbl} (sim={sim:.3f}, mc={mc})")

    if positive_parts:
        pos_text = " ".join(positive_parts)
        print(f"[TextSteering] Encoding positive: '{pos_text[:80]}'")
        _process(pos_text, "boost", top_k)

    if negative_parts:
        neg_text = " ".join(negative_parts)
        print(f"[TextSteering] Encoding negative: '{neg_text[:80]}'")
        _process(neg_text, "suppress", top_k)

    # Balance: ensure both boost and suppress are represented in top-K
    boosts = [f for f in top_features if f["direction"] == "boost"]
    supps = [f for f in top_features if f["direction"] == "suppress"]
    boosts.sort(key=lambda x: abs(x["weight"]), reverse=True)
    supps.sort(key=lambda x: abs(x["weight"]), reverse=True)

    if boosts and supps:
        min_per_dir = min(3, top_k // 2)
        guaranteed_b = boosts[:min_per_dir]
        guaranteed_s = supps[:min_per_dir]
        rest = [f for f in boosts[min_per_dir:] + supps[min_per_dir:]]
        rest.sort(key=lambda x: abs(x["weight"]), reverse=True)
        top_features = guaranteed_b + guaranteed_s + rest
        top_features = top_features[:top_k]
    else:
        top_features.sort(key=lambda x: abs(x["weight"]), reverse=True)
        top_features = top_features[:top_k]

    top_features.sort(key=lambda x: abs(x["weight"]), reverse=True)

    print(f"[TextSteering] Result: {len(adjustments)} neuron adjustments, {len(top_features)} top features")
    return adjustments, top_features


# ---------------------------------------------------------------------------
# Tag matching for display badges
# ---------------------------------------------------------------------------

def get_matched_tags(text: str, top_k: int = 5, model_id: str = "www_TopKSAE_8192") -> List[Tuple[str, float, str]]:
    """Get concept labels that best match the user's text (for tag badges)."""
    if not text or not text.strip():
        return []

    try:
        idx = _get_concept_index(model_id)
    except FileNotFoundError:
        return []

    model = _get_sbert()
    labels = idx["labels"]
    embeddings = idx["embeddings"]

    positive_parts, negative_parts = split_by_polarity(text)
    results = []
    seen = set()

    def _match(query_text: str, direction: str, n: int):
        emb = model.encode(query_text, normalize_embeddings=True)
        sims = _cosine_batch(emb, embeddings)
        ranking = np.argsort(sims)[::-1]
        count = 0
        for i in ranking:
            if count >= n:
                break
            sim = float(sims[i])
            if sim < 0.35:
                break
            lbl = labels[i]
            if lbl in seen:
                continue
            seen.add(lbl)
            results.append((lbl, sim, direction))
            count += 1

    if positive_parts:
        _match(" ".join(positive_parts), "increase", top_k)
    if negative_parts:
        _match(" ".join(negative_parts), "decrease", top_k)

    results.sort(key=lambda x: -x[1])
    return results[:top_k]


def get_neuron_labels(neuron_ids: List[int], model_id: str = "www_TopKSAE_8192") -> Dict[int, str]:
    """Get human-readable labels for neuron IDs from the LLM label cache."""
    llm_path = DATA_DIR / f"llm_labels_{model_id}_llm.json"

    labels = {}
    if llm_path.exists():
        with open(llm_path, 'r', encoding='utf-8') as f:
            raw = json.load(f)
        for nid in neuron_ids:
            info = raw.get(str(nid))
            if info:
                labels[nid] = info.get('label', f'Feature {nid}')
            else:
                labels[nid] = f'Feature {nid}'
    else:
        labels = {nid: f'Feature {nid}' for nid in neuron_ids}

    return labels


def get_feature_suggestions(text: str, top_k: int = 5) -> List[Tuple[str, float, str]]:
    """Alias for backward compat."""
    return get_matched_tags(text, top_k)
